[tool.ruff]
exclude = [".git", ".vscode",]

[tool.ruff.lint]
ignore = ["E402", "E501"]
unfixable = ["B"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

[tool.ruff.format]
quote-style = "single"
line-ending = "auto"
